
function sendMessage() {
  const userInput = document.getElementById("user-input").value;
  const outputBox = document.getElementById("chat-output");

  const reply = getReply(userInput);
  outputBox.innerText = reply;
  speak(reply);
}

function getReply(input) {
  input = input.toLowerCase();
  if (input.includes("chào")) return "Chào bạn! Mình là hướng dẫn viên ảo Thái Nguyên, mình có thể giúp gì?";
  if (input.includes("bạn là ai")) return "Mình là một AI hỗ trợ thông tin về Thái Nguyên trên mọi lĩnh vực!";
  if (input.includes("du lịch")) return "Bạn có thể khám phá Hồ Núi Cốc, hang Phượng Hoàng, suối Mỏ Gà và nhiều nơi khác!";
  if (input.includes("ẩm thực")) return "Ẩm thực Thái Nguyên nổi bật với bánh chưng Bờ Đậu, nem Đại Từ, cơm lam.";
  if (input.includes("lịch sử")) return "Thái Nguyên là nơi đặt căn cứ ATK thời kháng chiến chống Pháp.";
  if (input.includes("văn hóa")) return "Văn hóa Thái Nguyên phong phú với các dân tộc Tày, Nùng, Dao, H'Mông...";
  if (input.includes("địa lý")) return "Thái Nguyên là tỉnh trung du miền núi, giáp Bắc Kạn, Lạng Sơn, Hà Nội, Vĩnh Phúc.";
  if (input.includes("giáo dục")) return "Thái Nguyên có Đại học Thái Nguyên, là trung tâm đào tạo lớn ở miền Bắc.";
  if (input.includes("giao thông")) return "Bạn có thể đi bằng ô tô, xe khách, tàu hỏa từ Hà Nội rất tiện lợi.";
  if (input.includes("thời tiết")) return "Thái Nguyên có khí hậu cận nhiệt đới, mùa hè nóng và mưa nhiều.";
  if (input.includes("lễ hội")) return "Có lễ hội Lồng Tồng, hội Đền Đuổm, hội chọi trâu Phú Lương.";
  if (input.includes("dân số")) return "Dân số Thái Nguyên khoảng hơn 1,3 triệu người.";
  if (input.includes("thành phố")) return "Thành phố Thái Nguyên là trung tâm kinh tế, chính trị và văn hóa của tỉnh.";
  if (input.includes("địa danh")) return "Một số địa danh nổi bật gồm Hồ Núi Cốc, Đền Đuổm, ATK Định Hóa.";
  if (input.includes("công nghiệp")) return "Samsung đặt nhà máy lớn ở KCN Yên Bình - Thái Nguyên.";
  if (input.includes("nông nghiệp")) return "Thái Nguyên nổi bật với sản xuất chè, cây ăn quả và chăn nuôi.";
  if (input.includes("người dân")) return "Người Thái Nguyên thân thiện, cần cù và hiếu khách.";
  if (input.includes("dân tộc")) return "Có 8 dân tộc sinh sống như Kinh, Tày, Nùng, Dao, H'Mông...";
  if (input.includes("chè")) return "Chè Tân Cương là đặc sản nổi tiếng nhất với hương vị thanh mát, đậm đà.";
  if (input.includes("sản phẩm")) return "Sản phẩm đặc trưng: trà Thái, bánh chưng, cơm lam, mây tre đan.";
  if (input.includes("địa hình")) return "Địa hình chủ yếu là đồi núi thấp xen kẽ đồng bằng trung du.";
  if (input.includes("kinh tế")) return "Kinh tế đa dạng: công nghiệp, nông nghiệp, du lịch và dịch vụ.";
  if (input.includes("nổi tiếng")) return "Thái Nguyên nổi tiếng với trà, Hồ Núi Cốc và là nơi từng đặt ATK Định Hóa.";
  if (input.includes("giới thiệu")) return "Thái Nguyên là tỉnh trung du, nơi giao thoa giữa vùng núi và đồng bằng.";
  if (input.includes("đặc điểm")) return "Tỉnh có vị trí thuận lợi, nhiều tài nguyên thiên nhiên, người dân thân thiện.";
  if (input.includes("đi mùa nào")) return "Mùa thu (tháng 9–11) là thời điểm đẹp nhất để du lịch Thái Nguyên.";
  if (input.includes("tại sao gọi là đồi chè tân cương")) return "Đồi chè Tân Cương nổi tiếng với các đồi chè xanh mướt, là nơi sản xuất chè ngon nhất Việt Nam.";
  if (input.includes("tại sao gọi là đồi chè tân cương")) return "Đồi chè Tân Cương nổi tiếng với các đồi chè xanh mướt, là nơi sản xuất chè ngon nhất Việt Nam.";
  if (input.includes("có đi thăm các bản làng không")) return "Ở Thái Nguyên, bạn có thể tham quan các bản làng truyền thống như bản Tày, bản Nùng để khám phá đời sống văn hóa của người dân địa phương.";
  if (input.includes("chèo thuyền trên hồ núi cốc như thế nào")) return "Bạn có thể thuê thuyền chèo tay hoặc thuyền kayak trên hồ Núi Cốc để thưởng thức cảnh quan tuyệt đẹp từ mặt hồ.";
  if (input.includes("bảo tàng dân tộc học thái nguyên")) return "Bảo tàng dân tộc học Thái Nguyên lưu giữ văn hóa của hơn 50 dân tộc Việt Nam, đặc biệt là các dân tộc thiểu số vùng núi.";
  if (input.includes("lễ hội cầu mùa là gì")) return "Lễ hội Cầu Mùa là một lễ hội truyền thống của người Tày nhằm cầu cho mùa màng bội thu và cuộc sống bình an.";
  if (input.includes("bánh mì thái nguyên có gì đặc biệt")) return "Bánh mì ở Thái Nguyên có hương vị đặc biệt với nhân như chả, thịt quay, đặc biệt là bánh mì kẹp thịt lợn rừng.";
  if (input.includes("có quán ăn nào ngon ở thái nguyên không")) return "Bạn có thể thử các quán ăn nổi tiếng như Nhà Hàng Cơm Lam Tân Cương, Lẩu Thịt Lợn Rừng Thái Nguyên.";
  if (input.includes("trung tâm mua sắm thái nguyên có gì")) return "Ở Thái Nguyên có các trung tâm mua sắm lớn như Vincom Plaza, Thái Nguyên Center với nhiều cửa hàng thời trang, đồ điện tử và đồ gia dụng.";
  if (input.includes("chùa thái nguyên có những đâu")) return "Thái Nguyên có nhiều chùa nổi tiếng như Chùa Hang, Chùa Phú Lương, Chùa Đền Câu.";
  if (input.includes("dân tộc tày có những phong tục nào")) return "Dân tộc Tày có những phong tục như lễ cưới, lễ mừng nhà mới, đặc biệt là những ngày lễ hội cầu mùa.";
  if (input.includes("có thác nào khác ngoài khuôn tát không")) return "Ngoài thác Khuôn Tát, Thái Nguyên còn có thác Đát Đắng, thác Bản Hồ cũng rất đẹp và hoang sơ.";
  if (input.includes("bảo tàng thái nguyên mở cửa giờ nào")) return "Bảo tàng Thái Nguyên mở cửa từ 8:00 sáng đến 5:00 chiều từ thứ Hai đến thứ Sáu.";
  if (input.includes("có các dịch vụ lưu trú nào ở hồ núi cốc")) return "Hồ Núi Cốc có các dịch vụ lưu trú như khách sạn, nhà nghỉ và các khu nghỉ dưỡng bên hồ, rất tiện lợi cho du khách.";
  if (input.includes("có thể thuê xe đạp ở thái nguyên không")) return "Có, bạn có thể thuê xe đạp ở một số khu du lịch như hồ Núi Cốc và đồi chè Tân Cương để thăm quan.";
  if (input.includes("tôi có thể tham quan thái nguyên vào tháng mấy")) return "Bạn có thể tham quan Thái Nguyên quanh năm, nhưng mùa thu là thời điểm lý tưởng nhất với thời tiết mát mẻ và cảnh sắc tuyệt vời.";
  if (input.includes("các điểm du lịch sinh thái ở thái nguyên")) return "Thái Nguyên có các điểm du lịch sinh thái nổi bật như hồ Núi Cốc, thác Khuôn Tát, và khu sinh thái Phú Lương.";
  if (input.includes("đi thái nguyên vào mùa nào đẹp nhất")) return "Mùa thu là thời điểm đẹp nhất để tham quan Thái Nguyên, khi thời tiết mát mẻ và các loài hoa đua nở.";
  if (input.includes("thái nguyên có gì để tham quan vào cuối tuần")) return "Cuối tuần, bạn có thể tham quan hồ Núi Cốc, đồi chè Tân Cương, thác Khuôn Tát, hoặc tham gia các lễ hội truyền thống.";
  if (input.includes("có các hoạt động gì thú vị ở thái nguyên")) return "Bạn có thể tham gia các hoạt động như chèo thuyền, cắm trại, tham quan các khu sinh thái và tham gia các lễ hội địa phương.";
  if (input.includes("có thể đi đâu vào buổi tối ở thái nguyên")) return "Vào buổi tối, bạn có thể thưởng thức các món ăn vặt tại các chợ đêm hoặc ghé thăm các quán cà phê và nhà hàng trong thành phố.";
  if (input.includes("trẻ em có thể làm gì ở thái nguyên")) return "Trẻ em có thể vui chơi ở khu vui chơi Hồ Núi Cốc, vườn thú, tham gia các trò chơi ngoài trời tại các khu du lịch.";
  if (input.includes("tại sao thái nguyên lại nổi tiếng với chè tân cương")) return "Chè Tân Cương nổi tiếng vì có hương vị đặc biệt, được trồng ở vùng đất có khí hậu và thổ nhưỡng lý tưởng để tạo ra những lá chè thơm ngon.";
  if (input.includes("bánh chưng bờ đậu có gì đặc biệt")) return "Bánh chưng Bờ Đậu được làm từ nếp cái hoa vàng và gói bằng lá dong, có hương vị rất đặc trưng và là món ăn truyền thống trong dịp Tết.";
  if (input.includes("các khu du lịch ở thái nguyên")) return "Các khu du lịch nổi tiếng ở Thái Nguyên bao gồm hồ Núi Cốc, thác Khuôn Tát, đồi chè Tân Cương và khu sinh thái Phú Lương.";
  if (input.includes("chơi gì ở hồ núi cốc")) return "Ở hồ Núi Cốc, bạn có thể tham gia các hoạt động như chèo thuyền, câu cá, tham quan vườn thú, hoặc tham gia các trò chơi giải trí tại công viên.";
  if (input.includes("thái nguyên có những lễ hội gì")) return "Thái Nguyên có nhiều lễ hội truyền thống như lễ hội Lồng Tồng, lễ hội Cầu Mùa, lễ hội Đền Đuổm.";
  if (input.includes("có các món ăn đặc trưng nào ở thái nguyên")) return "Thái Nguyên nổi tiếng với các món ăn như cơm lam, thịt lợn rừng, bánh chưng Bờ Đậu, và đặc biệt là chè Tân Cương.";
  if (input.includes("hồ núi cốc")) return "Hồ Núi Cốc là một trong những điểm du lịch nổi tiếng của Thái Nguyên. Nơi đây có phong cảnh tuyệt đẹp, bao gồm hồ nước trong xanh, các đồi núi xanh mướt, và nhiều hoạt động thú vị như chèo thuyền, cắm trại, và tham quan vườn thú. Cũng có một khu vui chơi giải trí và công viên nước phục vụ cho mọi lứa tuổi.";
  if (input.includes("đồi chè tân cương")) return "Đồi chè Tân Cương là một điểm du lịch nổi tiếng, đặc biệt là đối với những người yêu thích thiên nhiên. Đây là nơi sản xuất chè nổi tiếng với những đồi chè xanh mướt, nơi du khách có thể tham gia các hoạt động tham quan, chụp ảnh và tìm hiểu về quy trình sản xuất chè.";
  if (input.includes("thác khuôn tát")) return "Thác Khuôn Tát nằm trong khu vực xã Phú Lương, Thái Nguyên, là một địa điểm lý tưởng cho những ai yêu thích du lịch sinh thái. Nơi đây có khung cảnh hoang sơ với thác nước đổ từ trên cao, bao quanh là rừng cây và đá vôi tạo nên một không gian trong lành, thích hợp cho các hoạt động leo núi và dã ngoại.";
  if (input.includes("thác đát đắng")) return "Thác Đát Đắng thuộc xã Quân Chu, huyện Định Hóa. Thác nước này nổi bật với vẻ đẹp hùng vĩ, với làn nước trong vắt đổ xuống từ trên cao tạo thành các dòng suối trong xanh, bao quanh là thiên nhiên hoang sơ. Đây là một điểm đến lý tưởng cho những ai yêu thích khám phá và tìm về với thiên nhiên.";
  if (input.includes("hang phượng hoàng")) return "Hang Phượng Hoàng là một trong những địa danh kỳ bí của Thái Nguyên, nằm tại xã Phú Linh. Hang động này có cấu trúc đá vôi độc đáo, với những nhũ đá rủ xuống từ trần và các hình thù kỳ lạ. Nơi đây không chỉ hấp dẫn khách du lịch bởi vẻ đẹp thiên nhiên mà còn gắn liền với nhiều huyền thoại dân gian.";
  if (input.includes("khu du lịch hồ núi cốc")) return "Khu du lịch Hồ Núi Cốc không chỉ có phong cảnh thiên nhiên tuyệt đẹp mà còn có nhiều hoạt động giải trí thú vị. Du khách có thể tham gia các trò chơi như đạp vịt, chèo thuyền kayak, hoặc tham gia các trò chơi ở công viên nước. Nơi đây cũng có các khu nghỉ dưỡng, khách sạn để du khách có thể nghỉ ngơi và thư giãn.";
  if (input.includes("bảo tàng các dân tộc việt nam")) return "Bảo tàng Các Dân Tộc Việt Nam tại Thái Nguyên là nơi lưu giữ và trưng bày những hiện vật văn hóa của 54 dân tộc Việt Nam. Bảo tàng này là một địa điểm lý tưởng để tìm hiểu về lịch sử, văn hóa và phong tục tập quán của các dân tộc thiểu số ở Việt Nam, đặc biệt là các dân tộc sống ở Thái Nguyên.";
  if (input.includes("chùa hang")) return "Chùa Hang Thái Nguyên là một ngôi chùa nổi tiếng nằm trên dãy núi Phú Lương. Chùa này có cảnh sắc tuyệt đẹp với khung cảnh yên bình, tĩnh lặng và những di tích lịch sử đặc biệt. Đây là một trong những điểm đến tâm linh thu hút du khách bởi không gian thanh tịnh và khí hậu mát mẻ.";
  if (input.includes("đền đuổm")) return "Đền Đuổm là một di tích lịch sử văn hóa nổi bật của Thái Nguyên, được xây dựng để thờ Dương Tự Minh, một vị tướng tài của triều Lý. Đền nằm trên đỉnh đồi Đuổm, từ đây du khách có thể nhìn ra toàn cảnh khu vực xung quanh. Đây là một điểm đến linh thiêng và cũng là nơi tổ chức các lễ hội truyền thống của địa phương.";
  if (input.includes("khu sinh thái phú lương")) return "Khu sinh thái Phú Lương là một địa điểm du lịch sinh thái nổi tiếng của Thái Nguyên. Nơi đây có khung cảnh thiên nhiên tươi đẹp, với rừng cây, thác nước và các khu vực cắm trại lý tưởng. Du khách có thể tham gia các hoạt động như trekking, tham quan hệ sinh thái rừng, hoặc đơn giản là thư giãn trong không gian yên bình.";
  if (input.includes("làng nghề chè tân cương")) return "Làng nghề chè Tân Cương là nơi sản xuất chè nổi tiếng nhất Thái Nguyên. Du khách có thể tham quan các vườn chè, tìm hiểu về quy trình chế biến chè, và thưởng thức những tách chè ngon. Đây là một trong những điểm đến hấp dẫn dành cho những ai yêu thích văn hóa trà.";
  if (input.includes("đền thượng thái nguyên")) return "Đền Thượng Thái Nguyên là một di tích lịch sử nổi bật, được xây dựng để thờ các vị thần linh bảo vệ đất nước. Đền nằm trên đỉnh đồi, không chỉ có giá trị tâm linh mà còn là nơi du khách có thể thưởng ngoạn toàn cảnh thành phố Thái Nguyên. Nơi đây có không gian rộng rãi và yên tĩnh, rất thích hợp cho các hoạt động du lịch tâm linh.";
  if (input.includes("khu du lịch sinh thái hồ ghềnh chè")) return "Khu du lịch sinh thái Hồ Ghềnh Chè ở Tân Cương là một địa điểm lý tưởng để thư giãn và tận hưởng thiên nhiên. Du khách có thể tham gia các hoạt động như cắm trại, chèo thuyền và ngắm cảnh hoàng hôn trên hồ. Đây cũng là một địa điểm tuyệt vời để thưởng thức chè Tân Cương và các món ăn đặc sản của vùng đất này.";
  if (input.includes("làng nghề bánh chưng bờ đậu")) return "Làng nghề bánh chưng Bờ Đậu là một trong những làng nghề truyền thống nổi tiếng của Thái Nguyên. Tại đây, du khách có thể tham quan quy trình làm bánh chưng và thưởng thức những chiếc bánh chưng đặc biệt với hương vị thơm ngon, nếp dẻo, và nhân đậu xanh, thịt mỡ rất đậm đà.";
  if (input.includes("hồ tân lập")) return "Hồ Tân Lập là một điểm du lịch mới nổi ở Thái Nguyên, nơi có phong cảnh thơ mộng và không gian tĩnh lặng. Hồ nước này bao quanh bởi rừng cây xanh mướt, là nơi lý tưởng cho các hoạt động câu cá, chèo thuyền, hoặc chỉ đơn giản là dạo bộ thư giãn trong thiên nhiên.";
  if (input.includes("phố cổ thái nguyên")) return "Phố cổ Thái Nguyên là nơi lưu giữ nhiều kiến trúc cổ xưa, đặc biệt là những ngôi nhà mang đậm nét kiến trúc Pháp và truyền thống của người Việt. Đây là một điểm đến thú vị cho những ai muốn tìm hiểu về lịch sử và văn hóa của thành phố Thái Nguyên.";  
  if (input.includes("Ho Nui Coc")) return "Ho Nui Coc is one of the most famous tourist spots in Thai Nguyen. It offers stunning scenery, including a clear lake, lush hills, and various activities such as boating, camping, and visiting the zoo. There is also an amusement park and a water park for all ages.";
  if (input.includes("Ho Nui Coc")) return "Ho Nui Coc is one of the most famous tourist spots in Thai Nguyen. It offers stunning scenery, including a clear lake, lush hills, and various activities such as boating, camping, and visiting the zoo. There is also an amusement park and a water park for all ages.";
  if (input.includes("Tan Cuong Tea Hill")) return "Tan Cuong Tea Hill is a famous tourist destination, especially for nature lovers. This place is known for its lush tea hills, where visitors can take part in sightseeing, photography, and learn about the tea production process.";
  if (input.includes("Khuon Tat Waterfall")) return "Khuon Tat Waterfall, located in Phu Luong Commune, Thai Nguyen, is an ideal destination for eco-tourism. The place features magnificent natural beauty with the waterfall cascading from above, surrounded by forests and limestone rocks, offering a fresh environment perfect for hiking and picnicking.";
  if (input.includes("Dat Dang Waterfall")) return "Dat Dang Waterfall is located in Quan Chu Commune, Dinh Hoa District. The waterfall stands out for its magnificent beauty, with crystal-clear water cascading from high above, surrounded by pristine nature. It is an ideal destination for exploration and nature lovers.";
  if (input.includes("Phuong Hoang Cave")) return "Phuong Hoang Cave is one of the mysterious landmarks of Thai Nguyen, located in Phu Linh Commune. This cave features unique limestone formations with stalactites and stalagmites in various shapes. It is an attractive spot for both nature lovers and those interested in local legends.";
  if (input.includes("Ho Nui Coc Tourism Area")) return "The Ho Nui Coc tourism area not only offers beautiful scenery but also a range of exciting activities. Visitors can enjoy activities such as pedal boating, kayaking, or playing in the water park. There are also resorts and hotels for visitors to relax and stay overnight.";
  if (input.includes("Vietnamese Ethnic Museum")) return "The Vietnamese Ethnic Museum in Thai Nguyen is a place to preserve and display cultural artifacts from the 54 Vietnamese ethnic groups. This museum is an ideal destination for learning about the history, culture, and customs of ethnic minorities in Vietnam, especially those living in Thai Nguyen.";
  if (input.includes("Chua Hang Temple")) return "Chua Hang Temple is a famous temple located on Phu Luong Mountain in Thai Nguyen. The temple offers a peaceful environment with its unique architecture, historical significance, and stunning views of the surrounding area. It is an important religious site for both locals and visitors.";
  if (input.includes("Den Duom Temple")) return "Den Duom Temple is a prominent historical and cultural relic in Thai Nguyen, dedicated to Dương Tự Minh, a talented general from the Ly Dynasty. The temple is located atop Duom Hill, offering panoramic views of the surrounding area. It is an important spiritual site and is also a venue for local festivals.";
  if (input.includes("Phu Luong Ecotourism Area")) return "Phu Luong Ecotourism Area is a famous eco-tourism destination in Thai Nguyen, with beautiful landscapes including forests, waterfalls, and ideal camping spots. Visitors can participate in activities such as trekking, exploring the forest ecosystem, or simply relaxing in the peaceful environment.";
  if (input.includes("Tan Cuong Tea Village")) return "Tan Cuong Tea Village is known as the birthplace of the famous Thai Nguyen tea. Visitors can explore the tea plantations, learn about the tea-making process, and taste the finest tea. This is a popular spot for those who love tea culture.";
  if (input.includes("Den Thuong Temple")) return "Den Thuong Temple is an important historical and cultural site in Thai Nguyen, dedicated to the deities who protected the country. The temple is located on a hilltop, offering panoramic views of the city. It is a peaceful site, perfect for those who enjoy spiritual tourism.";
  if (input.includes("Ghenh Che Lake Tourism Area")) return "Ghenh Che Lake in Tan Cuong is an ideal location for relaxation and enjoying nature. Visitors can participate in activities such as camping, boating, and watching the sunset over the lake. It is also a great place to sample Thai Nguyen tea and local specialties.";
  if (input.includes("Banh Chung Bo Dau Village")) return "Banh Chung Bo Dau Village is known for its traditional Banh Chung making. Here, visitors can witness the process of making these delicious rice cakes and taste the traditional Banh Chung with its fragrant sticky rice and pork filling, a special local delicacy.";
  if (input.includes("Tan Lap Lake")) return "Tan Lap Lake is a newly discovered tourist destination in Thai Nguyen with scenic beauty and a peaceful atmosphere. The lake is surrounded by lush trees, making it a perfect place for fishing, boating, or simply strolling in nature.";
  if (input.includes("Thai Nguyen Old Quarter")) return "The Old Quarter of Thai Nguyen is a place that preserves many ancient buildings, particularly those with French architecture. It is an interesting spot for those who wish to learn about the history and culture of Thai Nguyen through its traditional and colonial architecture.";
  if (input.includes("Suoi Mo")) return "Suoi Mo (Moc Stream) is a beautiful ecological tourist destination located in Vo Nhai District, Thai Nguyen. The stream flows through lush forests, creating a peaceful atmosphere with fresh air and clear water. It is a great spot for hiking, picnicking, and experiencing nature.";
  if (input.includes("hồ Núi Cốc")) return "Hồ Núi Cốc là một trong những địa điểm du lịch nổi bật của Thái Nguyên, nổi tiếng với cảnh quan thiên nhiên tuyệt đẹp và truyền thuyết về nàng Công và chàng Cốc. Đây là địa điểm lý tưởng cho du lịch sinh thái, dã ngoại và tham quan.";
  if (input.includes("đồi chè Tân Cương")) return "Đồi chè Tân Cương nổi tiếng với những cánh đồng chè xanh mướt và phong cảnh hữu tình. Đây là nơi sản xuất chè nổi tiếng, bạn có thể tham quan và tìm hiểu quy trình sản xuất chè.";
  if (input.includes("khu du lịch Hồ Núi Cốc")) return "Khu du lịch Hồ Núi Cốc có nhiều hoạt động thú vị như cắm trại, tham quan công viên động vật, đi thuyền trên hồ và thưởng thức các món ăn đặc sản vùng miền.";
  if (input.includes("thác Khuôn Tát")) return "Thác Khuôn Tát nằm ở xã Phúc Xuân, thành phố Thái Nguyên. Đây là một trong những thác nước đẹp và hoang sơ nhất của vùng đất Thái Nguyên, rất thích hợp cho những chuyến đi khám phá thiên nhiên.";
  if (input.includes("thác Đát Đắng")) return "Thác Đát Đắng nằm tại xã Tân Thành, huyện Phú Lương, Thái Nguyên. Thác nước này nổi tiếng với cảnh quan hoang sơ và nước trong vắt, thu hút nhiều du khách đến tham quan và chụp ảnh.";
  if (input.includes("Hồ Ghềnh Chè")) return "Hồ Ghềnh Chè ở Tân Cương là một địa điểm lý tưởng cho những chuyến dã ngoại, cắm trại và ngắm hoàng hôn. Hồ nước này bao quanh là những đồi chè xanh, tạo nên một khung cảnh thiên nhiên tuyệt đẹp.";
  if (input.includes("đền Đuổm")) return "Đền Đuổm là một di tích lịch sử nổi tiếng của Thái Nguyên, thờ Dương Tự Minh, một vị tướng tài của thời Lý. Đền có kiến trúc cổ kính và nằm trên một ngọn núi cao, giúp du khách tận hưởng cảnh quan tuyệt đẹp của vùng đất này.";
  if (input.includes("ATK Định Hóa")) return "ATK Định Hóa là một di tích lịch sử quan trọng, nơi Bác Hồ đã sống và làm việc trong thời kỳ kháng chiến chống Pháp. Đây là địa điểm không thể bỏ qua đối với những ai muốn tìm hiểu về lịch sử cách mạng của Việt Nam.";
  if (input.includes("bảo tàng các dân tộc Việt Nam")) return "Bảo tàng các dân tộc Việt Nam tọa lạc tại Thái Nguyên, nơi lưu giữ những hiện vật văn hóa của 54 dân tộc Việt Nam. Đây là một điểm đến lý tưởng để tìm hiểu về sự đa dạng văn hóa của đất nước.";
  if (input.includes("vườn quốc gia Tam Đảo")) return "Vườn quốc gia Tam Đảo, nằm một phần tại Thái Nguyên, nổi tiếng với hệ sinh thái phong phú và cảnh quan thiên nhiên tuyệt đẹp. Đây là nơi lý tưởng cho những ai yêu thích du lịch sinh thái và khám phá thiên nhiên.";
  if (input.includes("phố cổ Phú Bình")) return "Phố cổ Phú Bình là một trong những khu vực có nhiều giá trị lịch sử và văn hóa ở Thái Nguyên. Du khách có thể tham quan các di tích cổ kính và tìm hiểu về lịch sử phát triển của vùng đất này.";
  if (input.includes("khu du lịch Sinh Thái Lũng Vân")) return "Khu du lịch sinh thái Lũng Vân là một khu vực nổi tiếng ở Thái Nguyên với thiên nhiên hoang sơ, không khí trong lành và các hoạt động dã ngoại thú vị. Đây là địa điểm lý tưởng cho những ai yêu thích sự yên bình và gần gũi với thiên nhiên.";
  if (input.includes("hồ Đại Tu")) return "Hồ Đại Tu nằm ở huyện Đại Từ, là một trong những hồ nước lớn ở Thái Nguyên. Hồ nước này có không gian rộng lớn, phù hợp cho các hoạt động thư giãn, câu cá và thưởng ngoạn cảnh quan thiên nhiên.";
  if (input.includes("chùa Phú Linh")) return "Chùa Phú Linh nằm trên đỉnh núi Phú Linh, là một trong những ngôi chùa cổ nổi tiếng của Thái Nguyên. Đến đây, du khách có thể chiêm bái, tham quan và ngắm nhìn toàn cảnh thành phố Thái Nguyên từ trên cao.";
  if (input.includes("thác Mã Pí Lèng Thái Nguyên")) return "Thác Mã Pí Lèng Thái Nguyên nằm ở huyện Đồng Hỷ, là một trong những thác nước đẹp nhất vùng núi Bắc Bộ. Đây là địa điểm lý tưởng để bạn thưởng ngoạn thiên nhiên và tham gia các hoạt động mạo hiểm như leo núi và trekking.";
  if (input.includes("suối Mỏ")) return "Suối Mỏ nằm ở huyện Võ Nhai, Thái Nguyên. Đây là một điểm du lịch sinh thái nổi tiếng với khung cảnh thiên nhiên hùng vĩ, nước suối trong xanh, là nơi lý tưởng để du khách thư giãn và tắm suối.";
  if (input.includes("thành phố Thái Nguyên")) return "Thành phố Thái Nguyên là trung tâm hành chính, văn hóa và kinh tế của tỉnh Thái Nguyên. Du khách có thể tham quan các địa điểm như chợ Thái Nguyên, bảo tàng, và các công viên đẹp.";
  if (input.includes("chợ Thái Nguyên")) return "Chợ Thái Nguyên là một trong những chợ truyền thống lớn của thành phố. Đây là nơi bạn có thể mua sắm đặc sản, chè Tân Cương và nhiều món quà lưu niệm độc đáo của vùng đất này.";
  if (input.includes("khu du lịch Thung Nai")) return "Khu du lịch Thung Nai, nằm ở huyện Phú Bình, Thái Nguyên, là một địa điểm lý tưởng cho các chuyến đi dã ngoại. Nơi đây nổi tiếng với hồ nước xanh biếc và cảnh quan thiên nhiên thơ mộng.";
  if (input.includes("động Phượng Hoàng")) return "Động Phượng Hoàng là một hang động kỳ vĩ nằm tại xã Hợp Thành, Thái Nguyên. Đây là một trong những điểm du lịch hấp dẫn, với hệ thống thạch nhũ độc đáo và không gian yên tĩnh.";
  if (input.includes("đền Lồng Tồng")) return "Lễ hội Lồng Tồng là lễ hội nổi tiếng của người Tày tại Thái Nguyên, được tổ chức vào mùa xuân để cầu mùa màng bội thu. Đền Lồng Tồng là nơi tổ chức các nghi lễ tôn vinh các vị thần của người dân tộc Tày.";
  if (input.includes("hồ Suối Mỡ")) return "Hồ Suối Mỡ, nằm ở huyện Phú Lương, Thái Nguyên, nổi tiếng với vẻ đẹp hoang sơ và là địa điểm tuyệt vời cho những ai yêu thích thiên nhiên và cắm trại.";
  if (input.includes("khu di tích ATK")) return "Khu di tích ATK Định Hóa là một trong những điểm di tích lịch sử quan trọng ở Thái Nguyên, nơi Bác Hồ đã từng làm việc trong thời kỳ kháng chiến chống Pháp.";
  if (input.includes("Bảo tàng Thái Nguyên")) return "Bảo tàng Thái Nguyên lưu giữ các hiện vật lịch sử và văn hóa đặc trưng của tỉnh. Đây là địa điểm thú vị cho những ai muốn tìm hiểu về lịch sử và văn hóa Thái Nguyên.";
  if (input.includes("khu bảo tồn thiên nhiên Na Hang")) return "Khu bảo tồn thiên nhiên Na Hang, nằm gần biên giới Thái Nguyên và Tuyên Quang, nổi bật với hệ sinh thái phong phú, núi non hùng vĩ và hệ động thực vật quý hiếm.";
  if (input.includes("đền Hùng Thái Nguyên")) return "Đền Hùng Thái Nguyên là một địa điểm lịch sử tôn vinh các vị vua Hùng, nơi tổ chức các lễ hội lớn vào mùa xuân để tưởng nhớ các vị vua sáng lập nước Việt.";
  if (input.includes("hồ Đại Từ")) return "Hồ Đại Từ, nằm ở huyện Đại Từ, là một hồ nước lớn, có cảnh quan hữu tình, thích hợp cho các hoạt động câu cá và thư giãn cuối tuần.";
  if (input.includes("phố cổ Phú Bình")) return "Phố cổ Phú Bình nổi tiếng với những ngôi nhà cổ kính và kiến trúc đặc trưng. Đây là nơi lý tưởng để tìm hiểu về lịch sử và văn hóa của vùng đất Thái Nguyên.";
  if (input.includes("đặc sản thái nguyên")) return "Thái Nguyên nổi tiếng với các đặc sản như chè Tân Cương, cơm lam, thịt lợn rừng, bánh chưng Bờ Đậu và mèn mén. Đây đều là những món ăn đặc trưng của vùng đất này.";
  if (input.includes("chè tân cương")) return "Chè Tân Cương là một trong những loại chè nổi tiếng nhất ở Thái Nguyên, được trồng tại xã Tân Cương, huyện Đại Từ. Chè có hương thơm đặc trưng, vị ngọt thanh, là đặc sản được yêu thích của người dân nơi đây.";
  if (input.includes("cơm lam")) return "Cơm lam là món ăn đặc sản của Thái Nguyên, được nấu trong ống tre, gạo nếp được nấu chín mềm, dẻo và có hương vị rất đặc biệt. Thường ăn kèm với thịt nướng hoặc cá suối.";
  if (input.includes("bánh chưng bờ đậu")) return "Bánh chưng Bờ Đậu là món bánh truyền thống của người dân Thái Nguyên. Bánh được làm từ nếp cái hoa vàng, nhân đậu xanh và thịt lợn. Bánh có vị ngọt thanh và thơm mùi lá dong, rất được ưa chuộng trong các dịp lễ Tết.";
  if (input.includes("thịt lợn rừng")) return "Thịt lợn rừng Thái Nguyên được nuôi thả tự nhiên, thịt rất chắc, thơm và ngọt. Thịt lợn rừng thường được chế biến thành các món nướng, hấp hoặc xào, rất ngon và bổ dưỡng.";
  if (input.includes("mèn mén")) return "Mèn mén là món ăn truyền thống của người dân tộc Tày ở Thái Nguyên. Đây là món cơm được nấu từ bột ngô, có thể ăn kèm với thịt lợn rừng, cá suối hoặc rau rừng, mang đậm hương vị núi rừng.";
  if (input.includes("canh chua cá suối")) return "Canh chua cá suối là món ăn đặc trưng của Thái Nguyên, cá suối được nấu với các loại gia vị như sả, ớt, và các loại rau rừng tạo nên hương vị chua thanh, ngọt mát rất đặc biệt.";
  if (input.includes("thắng cố")) return "Thắng cố là món ăn đặc sản của người dân tộc Tày, thường được chế biến từ thịt bò, lợn, kèm theo các loại gia vị đặc trưng. Món ăn này có hương vị đậm đà và rất được ưa chuộng trong các lễ hội của người dân tộc.";
  if (input.includes("bánh gai bờ đậu")) return "Bánh gai Bờ Đậu được làm từ lá gai, nếp và đậu xanh, có hương vị đặc biệt và rất thơm ngon. Món bánh này là đặc sản nổi tiếng của vùng Bờ Đậu, Thái Nguyên, thường được dùng trong các dịp lễ hội.";
  if (input.includes("cá nướng trui")) return "Cá nướng trui là món ăn đặc sản của Thái Nguyên, cá được nướng nguyên con trên than hoa, có thể ăn kèm với lá chanh, rau sống và gia vị. Món ăn này có vị ngọt thanh, thơm và rất đậm đà.";
  if (input.includes("rau rừng thái nguyên")) return "Rau rừng Thái Nguyên rất phong phú và đa dạng, bao gồm các loại như rau dền, măng tây, măng trúc, rau ngót. Các món ăn từ rau rừng thường rất tươi ngon và có hương vị đặc biệt.";
  if (input.includes("bánh cuốn thái nguyên")) return "Bánh cuốn Thái Nguyên là món ăn sáng phổ biến của người dân nơi đây, bánh cuốn được làm từ bột gạo mỏng, nhân thịt xay và mộc nhĩ, ăn kèm với nước mắm chua ngọt rất ngon miệng.";
  if (input.includes("cơm nắm gối")) return "Cơm nắm gối là món ăn độc đáo của Thái Nguyên, cơm được nắm thành hình vuông vức, ăn kèm với cá kho, thịt nướng hoặc rau củ. Đây là món ăn truyền thống, thường được mang theo trong các chuyến đi xa.";
  if (input.includes("xôi ngũ sắc")) return "Xôi ngũ sắc là món ăn đặc sắc của người Tày, với các loại xôi có màu sắc đa dạng như xôi đậu xanh, xôi ngô, xôi khoai, tạo nên một món ăn không chỉ ngon mà còn rất bắt mắt.";
  if (input.includes("bánh tẻ thái nguyên")) return "Bánh tẻ Thái Nguyên có vỏ bánh mềm mịn, nhân thịt lợn hoặc đậu xanh. Bánh thường được ăn kèm với nước mắm pha chua ngọt, rất ngon và dễ ăn.";
  if (input.includes("cơm chay thái nguyên")) return "Cơm chay Thái Nguyên thường được chế biến từ các nguyên liệu tươi sạch như rau củ, đậu, nấm, tạo thành những món ăn thanh đạm nhưng đầy đủ dưỡng chất. Món ăn này được nhiều người yêu thích trong những dịp lễ hội hoặc ăn kiêng.";
  if (input.includes("bánh bột lọc")) return "Bánh bột lọc Thái Nguyên là món ăn vặt phổ biến, với lớp bột mỏng bao bọc nhân tôm hoặc thịt, khi ăn có vị mềm dẻo, ngon miệng. Món bánh này thường được ăn kèm với nước mắm chua ngọt.";
  if (input.includes("bánh trôi thái nguyên")) return "Bánh trôi Thái Nguyên có nhân đậu xanh hoặc vừng, lớp ngoài dẻo mềm. Món bánh này thường được ăn vào các dịp Tết Nguyên Đán hoặc trong các lễ hội đặc biệt của người dân nơi đây.";
  if (input.includes("canh rau rừng")) return "Canh rau rừng Thái Nguyên thường được nấu với các loại rau rừng tươi ngon, tạo nên một món canh thanh mát, bổ dưỡng, có thể ăn kèm với cơm hoặc thịt kho.";
  if (input.includes("gà đồi thái nguyên")) return "Gà đồi Thái Nguyên là loại gà được nuôi thả tự nhiên trên đồi, thịt rất săn chắc, ngọt và thơm. Gà đồi thường được chế biến thành các món nướng hoặc hầm, rất thơm ngon.";
  if (input.includes("tôm suối thái nguyên")) return "Tôm suối Thái Nguyên là món ăn đặc sản của các vùng suối ở Thái Nguyên, tôm suối có vị ngọt, tươi ngon, thường được chế biến thành các món luộc, nướng hoặc xào.";
  if (input.includes("bánh xèo thái nguyên")) return "Bánh xèo Thái Nguyên là món ăn phổ biến trong các buổi tụ tập gia đình hoặc bạn bè, bánh được làm từ bột gạo pha với nước cốt dừa, nhân tôm, thịt và giá đỗ, ăn kèm với rau sống và nước mắm.";
  return "Mình chưa hiểu câu hỏi, bạn có thể hỏi cụ thể hơn nhé!";
 return "Mình chưa hiểu câu hỏi, bạn có thể hỏi cụ thể hơn nhé!";
}

function speak(text) {
  if ('speechSynthesis' in window) {
    const msg = new SpeechSynthesisUtterance(text);
    msg.lang = 'vi-VN';
    msg.pitch = 1;
    msg.rate = 1;
    msg.volume = 1;
    speechSynthesis.speak(msg);
  } else {
    alert("Trình duyệt của bạn không hỗ trợ giọng nói.");
  }
}
